### ISSUE TITLE
Committed files in build-ui cause confusion.

### ISSUE THREAD

**Issue by bemosior** [cdaniel/atlas2#112]
I'm not exactly an expert in webpack, but from my experience I'm pretty sure we shouldn't commit files to `build-ui`. Rather, it's much better to configure webpack to build everything in that folder fresh before the server starts up. Otherwise, we can easily get into a situation where over time the committed files drift from the files webpack would otherwise generate. As an example, the following files have drifted if I run webpack manually now:

```
	modified:   build-ui/js/canvas-wrapper.js
	modified:   build-ui/js/google-app.js
	modified:   build-ui/js/l-p-app.js
```
In #111, I had to hand-edit a minified js file in `build-ui` because changes to `src-ui/minimal-canvas/canvas.js` weren't being picked up and rebuilt by webpack. That's another negative side effect.

I can try to find some time in the near future to see what it would take to fix these issues.

**Comment by cdaniel** [comment]
Rendering maps in 'png' format serverside is not an easy task. I use phantomjs, which is a headless browser that runs in a separate process. Unfortunately, react-bootstrap and jsplumb are quite large libraries, and phantomjs needs a lot of time to parse them. During my first attempts to get it working, 10s (!) was required to render a simple map. Stripping symbols maps reduced that to 5s, but even than it was unacceptable.

I have created minimal-canvas, which does not offer any interactivity, but has minimal dependencies and is small. Maps are rendered in less than 1s. The drawback of this solution is that in the file [image-renderer.js](https://github.com/cdaniel/atlas2/blob/master/src-server/workspace/image-renderer.js) I need to assemble an html doc that is injected into phantomjs, and I use `fs.readFileSync` to get the precompiled script.

If it would be possible to rely on in-memory compilation, it would be great! 

Also, I have been trying to split the bundle into the `vendor` and `mapdata` parts to get rendering under 0.2s, because phantomjs would have to parse the large js only once, and then only map data would be swapped, but I have not managed to get this working. With fast map rendering, it could be possible to have map previews in multiple places, and a map list view like one attached below.
![screen shot 2017-06-08 at 09 32 58](https://user-images.githubusercontent.com/1265262/26917210-af27ca88-4c2d-11e7-8c49-eb4370dcf541.png)

**Comment by bemosior** [comment]
Behind every unexpected project characteristic, there is a real problem being solved with very good reasoning. Thanks for filling me in!

**Comment by cdaniel** [comment]
It does not mean it is impossible to make it memory based developer builds and get the same purpose. I just have no idea how to do it :-(

**Comment by cdaniel** [comment]
Actually, [Webpack middleware](https://webpack.github.io/docs/webpack-dev-middleware.html)  mentions [readable filesystem](https://webpack.github.io/docs/webpack-dev-middleware.html#middleware-filesystem). This could be used to do the trick in the dev mode. I'll look at this when I am done with variants & timelines.

**Comment by cdaniel** [comment]
@bemosior, could you double check if [this patch](https://github.com/cdaniel/atlas2/pull/114) works for you?

**Comment by bemosior** [comment]
That seems to work, nice! I'm wondering if we should eventually do have webpack manage the remaining files (css, fonts, etc.) as well, but those change so infrequently I'm not sure it's worth worrying about right now.

**Comment by cdaniel** [comment]
Patch released.
